name: Build PeyiTV APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Download Gradle 8.7
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH

      # ⬇️ Crée gradle.properties avec AndroidX activé
      - name: Create gradle.properties
        run: |
          cat > gradle.properties <<'EOF'
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
          android.nonTransitiveRClass=true
          EOF
          cat gradle.properties

      - name: Generate Gradle Wrapper (8.7)
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: PeyiTV-debug-apk
          path: app/build/outputs/apk/debug/*.apk
