name: Build PeyiTV APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Installe le SDK Android (cmdline-tools) et accepte les licences
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Installe Gradle (binaire système) uniquement pour générer un vrai wrapper
      - name: Install Gradle (for wrapper generation)
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle --version

      # Génère un wrapper propre (créera: gradlew, gradlew.bat, gradle/wrapper/*.jar, *.properties)
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      # Build APK debug avec le wrapper fraîchement généré
      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PeyiTV-debug-apk
          path: app/build/outputs/apk/debug/*.apk

